name: flutterapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  simple_animations: ^1.3.3
  cupertino_icons: ^0.1.2
  page_transition: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
   - images/one.jpg
   - images/two.jpg
   - images/three.jpg
   - images/background.png


  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Regular.ttf